name = "test-hello-world-5"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "test-hello-world-5_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "test-hello-world-5.wasm"
command = "npm run build:release"
